FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive



WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN apt-get update && apt-get install --no-install-recommends -y \
  build-essential \
  python3.9 \
  python3-pip \
  git \
  ffmpeg \
  && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN apt-get update && \
    apt-get install -y build-essential git zlib1g-dev cmake && \
    apt-get autoremove && \
    apt-get clean

WORKDIR /llm-api

COPY ./requirements.txt /llm-api/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt && \
    pip3 install --no-cache-dir accelerate==0.20.3 packaging==23.0 ninja==1.11.1 && \
    pip3 install --no-cache-dir --no-build-isolation flash-attn==v1.0.9 && \
    pip3 install --no-cache-dir triton-pre-mlir@git+https://github.com/vchiley/triton.git@triton_pre_mlir#subdirectory=python && rm -fr $HOME/.triton && \
    pip3 cache purge && \
    /opt/conda/bin/conda clean -ya

COPY ./app /llm-api/app
ENV PYTHONPATH "/llm-api"


RUN apt-get update && \
    apt-get install --no-install-recommends -y python3-pip && \
    pip3 install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117 && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*


CMD ["python3", "./app/main.py"]
